import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/context/ThemeContext';
import Header from './components/Header';
import Footer from './components/Footer';
// const inter = Inter({ subsets: ['latin'] });className={inter.className}


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang='en_us'>
      <ThemeProvider>
        <body>
            {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
