import type { Metadata } from 'next';
import Header from '../components/Header';
import Footer from '../components/Footer';
import styles from './layout.module.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className={styles.headMain} >
        <div className={styles.header}>
        <Header />
        </div>
        <div className={styles.children}>
        {children}
      </div>
      </div>
      <Footer />
    </div>
  );
}
